workflows:
  build_shopgp3:
    name: ShopGP3 App Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        KEY_PROPERTIES_PATH: android/key.properties
        KEYSTORE_PATH: android/app/shopgp3-release-key.jks
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Decode keystore
        script: |
          echo $KEYSTORE_BASE64 | base64 --decode > $KEYSTORE_PATH

      - name: Setup key.properties
        script: |
          echo "storeFile=${KEYSTORE_PATH}" > $KEY_PROPERTIES_PATH
          echo "storePassword=${STORE_PASSWORD}" >> $KEY_PROPERTIES_PATH
          echo "keyAlias=${KEY_ALIAS}" >> $KEY_PROPERTIES_PATH
          echo "keyPassword=${KEY_PASSWORD}" >> $KEY_PROPERTIES_PATH

      - name: Build Android AAB
        script: flutter build appbundle --release

      - name: Build iOS (sem assinatura automática)
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - jeff.gualter@gmail.com
